/* soapH.h
   Generated by gSOAP 2.7.9b from /home/veiko/MSSP_GW/src/MSSP_GW.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_xsd__int(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__positiveInteger
#define SOAP_TYPE_xsd__positiveInteger (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__positiveInteger(struct soap*, unsigned long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__positiveInteger(struct soap*, const unsigned long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__positiveInteger(struct soap*, const char*, int, const unsigned long *, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_get_xsd__positiveInteger(struct soap*, unsigned long *, const char*, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_in_xsd__positiveInteger(struct soap*, const char*, unsigned long *, const char*);

#ifndef SOAP_TYPE_unsignedLong
#define SOAP_TYPE_unsignedLong (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedLong(struct soap*, unsigned long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedLong(struct soap*, const unsigned long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedLong(struct soap*, const char*, int, const unsigned long *, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_get_unsignedLong(struct soap*, unsigned long *, const char*, const char*);
SOAP_FMAC3 unsigned long * SOAP_FMAC4 soap_in_unsignedLong(struct soap*, const char*, unsigned long *, const char*);

#ifndef SOAP_TYPE_mss__MessagingModeType
#define SOAP_TYPE_mss__MessagingModeType (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MessagingModeType(struct soap*, enum mss__MessagingModeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MessagingModeType(struct soap*, const enum mss__MessagingModeType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MessagingModeType(struct soap*, const char*, int, const enum mss__MessagingModeType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_mss__MessagingModeType2s(struct soap*, enum mss__MessagingModeType);
SOAP_FMAC3 enum mss__MessagingModeType * SOAP_FMAC4 soap_get_mss__MessagingModeType(struct soap*, enum mss__MessagingModeType *, const char*, const char*);
SOAP_FMAC3 enum mss__MessagingModeType * SOAP_FMAC4 soap_in_mss__MessagingModeType(struct soap*, const char*, enum mss__MessagingModeType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2mss__MessagingModeType(struct soap*, const char*, enum mss__MessagingModeType *);

#ifndef SOAP_TYPE_mss__SignatureProfileComparisonType
#define SOAP_TYPE_mss__SignatureProfileComparisonType (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__SignatureProfileComparisonType(struct soap*, enum mss__SignatureProfileComparisonType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__SignatureProfileComparisonType(struct soap*, const enum mss__SignatureProfileComparisonType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__SignatureProfileComparisonType(struct soap*, const char*, int, const enum mss__SignatureProfileComparisonType *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_mss__SignatureProfileComparisonType2s(struct soap*, enum mss__SignatureProfileComparisonType);
SOAP_FMAC3 enum mss__SignatureProfileComparisonType * SOAP_FMAC4 soap_get_mss__SignatureProfileComparisonType(struct soap*, enum mss__SignatureProfileComparisonType *, const char*, const char*);
SOAP_FMAC3 enum mss__SignatureProfileComparisonType * SOAP_FMAC4 soap_in_mss__SignatureProfileComparisonType(struct soap*, const char*, enum mss__SignatureProfileComparisonType *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2mss__SignatureProfileComparisonType(struct soap*, const char*, enum mss__SignatureProfileComparisonType *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_mss__MSS_USCOREStatusReq
#define SOAP_TYPE_mss__MSS_USCOREStatusReq (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MSS_USCOREStatusReq(struct soap*, const struct mss__MSS_USCOREStatusReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MSS_USCOREStatusReq(struct soap*, struct mss__MSS_USCOREStatusReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MSS_USCOREStatusReq(struct soap*, const struct mss__MSS_USCOREStatusReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MSS_USCOREStatusReq(struct soap*, const char*, int, const struct mss__MSS_USCOREStatusReq *, const char*);
SOAP_FMAC3 struct mss__MSS_USCOREStatusReq * SOAP_FMAC4 soap_get_mss__MSS_USCOREStatusReq(struct soap*, struct mss__MSS_USCOREStatusReq *, const char*, const char*);
SOAP_FMAC3 struct mss__MSS_USCOREStatusReq * SOAP_FMAC4 soap_in_mss__MSS_USCOREStatusReq(struct soap*, const char*, struct mss__MSS_USCOREStatusReq *, const char*);

#ifndef SOAP_TYPE_mss__MSS_USCOREStatusResp
#define SOAP_TYPE_mss__MSS_USCOREStatusResp (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MSS_USCOREStatusResp(struct soap*, const struct mss__MSS_USCOREStatusResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MSS_USCOREStatusResp(struct soap*, struct mss__MSS_USCOREStatusResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MSS_USCOREStatusResp(struct soap*, const struct mss__MSS_USCOREStatusResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MSS_USCOREStatusResp(struct soap*, const char*, int, const struct mss__MSS_USCOREStatusResp *, const char*);
SOAP_FMAC3 struct mss__MSS_USCOREStatusResp * SOAP_FMAC4 soap_get_mss__MSS_USCOREStatusResp(struct soap*, struct mss__MSS_USCOREStatusResp *, const char*, const char*);
SOAP_FMAC3 struct mss__MSS_USCOREStatusResp * SOAP_FMAC4 soap_in_mss__MSS_USCOREStatusResp(struct soap*, const char*, struct mss__MSS_USCOREStatusResp *, const char*);

#ifndef SOAP_TYPE_mss__MSS_USCORESignatureReq
#define SOAP_TYPE_mss__MSS_USCORESignatureReq (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MSS_USCORESignatureReq(struct soap*, const struct mss__MSS_USCORESignatureReq *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MSS_USCORESignatureReq(struct soap*, struct mss__MSS_USCORESignatureReq *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MSS_USCORESignatureReq(struct soap*, const struct mss__MSS_USCORESignatureReq *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MSS_USCORESignatureReq(struct soap*, const char*, int, const struct mss__MSS_USCORESignatureReq *, const char*);
SOAP_FMAC3 struct mss__MSS_USCORESignatureReq * SOAP_FMAC4 soap_get_mss__MSS_USCORESignatureReq(struct soap*, struct mss__MSS_USCORESignatureReq *, const char*, const char*);
SOAP_FMAC3 struct mss__MSS_USCORESignatureReq * SOAP_FMAC4 soap_in_mss__MSS_USCORESignatureReq(struct soap*, const char*, struct mss__MSS_USCORESignatureReq *, const char*);

#ifndef SOAP_TYPE_mss__MSS_USCORESignatureResp
#define SOAP_TYPE_mss__MSS_USCORESignatureResp (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MSS_USCORESignatureResp(struct soap*, const struct mss__MSS_USCORESignatureResp *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MSS_USCORESignatureResp(struct soap*, struct mss__MSS_USCORESignatureResp *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MSS_USCORESignatureResp(struct soap*, const struct mss__MSS_USCORESignatureResp *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MSS_USCORESignatureResp(struct soap*, const char*, int, const struct mss__MSS_USCORESignatureResp *, const char*);
SOAP_FMAC3 struct mss__MSS_USCORESignatureResp * SOAP_FMAC4 soap_get_mss__MSS_USCORESignatureResp(struct soap*, struct mss__MSS_USCORESignatureResp *, const char*, const char*);
SOAP_FMAC3 struct mss__MSS_USCORESignatureResp * SOAP_FMAC4 soap_in_mss__MSS_USCORESignatureResp(struct soap*, const char*, struct mss__MSS_USCORESignatureResp *, const char*);

#ifndef SOAP_TYPE_mss__SignatureType
#define SOAP_TYPE_mss__SignatureType (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__SignatureType(struct soap*, const struct mss__SignatureType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__SignatureType(struct soap*, struct mss__SignatureType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__SignatureType(struct soap*, const struct mss__SignatureType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__SignatureType(struct soap*, const char*, int, const struct mss__SignatureType *, const char*);
SOAP_FMAC3 struct mss__SignatureType * SOAP_FMAC4 soap_get_mss__SignatureType(struct soap*, struct mss__SignatureType *, const char*, const char*);
SOAP_FMAC3 struct mss__SignatureType * SOAP_FMAC4 soap_in_mss__SignatureType(struct soap*, const char*, struct mss__SignatureType *, const char*);

#ifndef SOAP_TYPE_mss__StatusType
#define SOAP_TYPE_mss__StatusType (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__StatusType(struct soap*, const struct mss__StatusType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__StatusType(struct soap*, struct mss__StatusType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__StatusType(struct soap*, const struct mss__StatusType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__StatusType(struct soap*, const char*, int, const struct mss__StatusType *, const char*);
SOAP_FMAC3 struct mss__StatusType * SOAP_FMAC4 soap_get_mss__StatusType(struct soap*, struct mss__StatusType *, const char*, const char*);
SOAP_FMAC3 struct mss__StatusType * SOAP_FMAC4 soap_in_mss__StatusType(struct soap*, const char*, struct mss__StatusType *, const char*);

#ifndef SOAP_TYPE_mss__StatusCodeType
#define SOAP_TYPE_mss__StatusCodeType (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__StatusCodeType(struct soap*, const struct mss__StatusCodeType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__StatusCodeType(struct soap*, struct mss__StatusCodeType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__StatusCodeType(struct soap*, const struct mss__StatusCodeType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__StatusCodeType(struct soap*, const char*, int, const struct mss__StatusCodeType *, const char*);
SOAP_FMAC3 struct mss__StatusCodeType * SOAP_FMAC4 soap_get_mss__StatusCodeType(struct soap*, struct mss__StatusCodeType *, const char*, const char*);
SOAP_FMAC3 struct mss__StatusCodeType * SOAP_FMAC4 soap_in_mss__StatusCodeType(struct soap*, const char*, struct mss__StatusCodeType *, const char*);

#ifndef SOAP_TYPE_mss__KeyReferenceType
#define SOAP_TYPE_mss__KeyReferenceType (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__KeyReferenceType(struct soap*, const struct mss__KeyReferenceType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__KeyReferenceType(struct soap*, struct mss__KeyReferenceType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__KeyReferenceType(struct soap*, const struct mss__KeyReferenceType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__KeyReferenceType(struct soap*, const char*, int, const struct mss__KeyReferenceType *, const char*);
SOAP_FMAC3 struct mss__KeyReferenceType * SOAP_FMAC4 soap_get_mss__KeyReferenceType(struct soap*, struct mss__KeyReferenceType *, const char*, const char*);
SOAP_FMAC3 struct mss__KeyReferenceType * SOAP_FMAC4 soap_in_mss__KeyReferenceType(struct soap*, const char*, struct mss__KeyReferenceType *, const char*);

#ifndef SOAP_TYPE_mss__MSSP_InfoType
#define SOAP_TYPE_mss__MSSP_InfoType (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MSSP_InfoType(struct soap*, const struct mss__MSSP_InfoType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MSSP_InfoType(struct soap*, struct mss__MSSP_InfoType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MSSP_InfoType(struct soap*, const struct mss__MSSP_InfoType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MSSP_InfoType(struct soap*, const char*, int, const struct mss__MSSP_InfoType *, const char*);
SOAP_FMAC3 struct mss__MSSP_InfoType * SOAP_FMAC4 soap_get_mss__MSSP_InfoType(struct soap*, struct mss__MSSP_InfoType *, const char*, const char*);
SOAP_FMAC3 struct mss__MSSP_InfoType * SOAP_FMAC4 soap_in_mss__MSSP_InfoType(struct soap*, const char*, struct mss__MSSP_InfoType *, const char*);

#ifndef SOAP_TYPE_mss__AP_InfoType
#define SOAP_TYPE_mss__AP_InfoType (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__AP_InfoType(struct soap*, const struct mss__AP_InfoType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__AP_InfoType(struct soap*, struct mss__AP_InfoType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__AP_InfoType(struct soap*, const struct mss__AP_InfoType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__AP_InfoType(struct soap*, const char*, int, const struct mss__AP_InfoType *, const char*);
SOAP_FMAC3 struct mss__AP_InfoType * SOAP_FMAC4 soap_get_mss__AP_InfoType(struct soap*, struct mss__AP_InfoType *, const char*, const char*);
SOAP_FMAC3 struct mss__AP_InfoType * SOAP_FMAC4 soap_in_mss__AP_InfoType(struct soap*, const char*, struct mss__AP_InfoType *, const char*);

#ifndef SOAP_TYPE_mss__mssURIType
#define SOAP_TYPE_mss__mssURIType (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__mssURIType(struct soap*, const struct mss__mssURIType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__mssURIType(struct soap*, struct mss__mssURIType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__mssURIType(struct soap*, const struct mss__mssURIType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__mssURIType(struct soap*, const char*, int, const struct mss__mssURIType *, const char*);
SOAP_FMAC3 struct mss__mssURIType * SOAP_FMAC4 soap_get_mss__mssURIType(struct soap*, struct mss__mssURIType *, const char*, const char*);
SOAP_FMAC3 struct mss__mssURIType * SOAP_FMAC4 soap_in_mss__mssURIType(struct soap*, const char*, struct mss__mssURIType *, const char*);

#ifndef SOAP_TYPE_mss__DigestAlgAndValueType
#define SOAP_TYPE_mss__DigestAlgAndValueType (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__DigestAlgAndValueType(struct soap*, const struct mss__DigestAlgAndValueType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__DigestAlgAndValueType(struct soap*, struct mss__DigestAlgAndValueType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__DigestAlgAndValueType(struct soap*, const struct mss__DigestAlgAndValueType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__DigestAlgAndValueType(struct soap*, const char*, int, const struct mss__DigestAlgAndValueType *, const char*);
SOAP_FMAC3 struct mss__DigestAlgAndValueType * SOAP_FMAC4 soap_get_mss__DigestAlgAndValueType(struct soap*, struct mss__DigestAlgAndValueType *, const char*, const char*);
SOAP_FMAC3 struct mss__DigestAlgAndValueType * SOAP_FMAC4 soap_in_mss__DigestAlgAndValueType(struct soap*, const char*, struct mss__DigestAlgAndValueType *, const char*);

#ifndef SOAP_TYPE_DigestMethodType
#define SOAP_TYPE_DigestMethodType (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_DigestMethodType(struct soap*, const struct DigestMethodType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_DigestMethodType(struct soap*, struct DigestMethodType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_DigestMethodType(struct soap*, const struct DigestMethodType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_DigestMethodType(struct soap*, const char*, int, const struct DigestMethodType *, const char*);
SOAP_FMAC3 struct DigestMethodType * SOAP_FMAC4 soap_get_DigestMethodType(struct soap*, struct DigestMethodType *, const char*, const char*);
SOAP_FMAC3 struct DigestMethodType * SOAP_FMAC4 soap_in_DigestMethodType(struct soap*, const char*, struct DigestMethodType *, const char*);

#ifndef SOAP_TYPE_mss__MobileUserType
#define SOAP_TYPE_mss__MobileUserType (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MobileUserType(struct soap*, const struct mss__MobileUserType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MobileUserType(struct soap*, struct mss__MobileUserType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MobileUserType(struct soap*, const struct mss__MobileUserType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MobileUserType(struct soap*, const char*, int, const struct mss__MobileUserType *, const char*);
SOAP_FMAC3 struct mss__MobileUserType * SOAP_FMAC4 soap_get_mss__MobileUserType(struct soap*, struct mss__MobileUserType *, const char*, const char*);
SOAP_FMAC3 struct mss__MobileUserType * SOAP_FMAC4 soap_in_mss__MobileUserType(struct soap*, const char*, struct mss__MobileUserType *, const char*);

#ifndef SOAP_TYPE_mss__MeshMemberType
#define SOAP_TYPE_mss__MeshMemberType (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__MeshMemberType(struct soap*, const struct mss__MeshMemberType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__MeshMemberType(struct soap*, struct mss__MeshMemberType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__MeshMemberType(struct soap*, const struct mss__MeshMemberType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__MeshMemberType(struct soap*, const char*, int, const struct mss__MeshMemberType *, const char*);
SOAP_FMAC3 struct mss__MeshMemberType * SOAP_FMAC4 soap_get_mss__MeshMemberType(struct soap*, struct mss__MeshMemberType *, const char*, const char*);
SOAP_FMAC3 struct mss__MeshMemberType * SOAP_FMAC4 soap_in_mss__MeshMemberType(struct soap*, const char*, struct mss__MeshMemberType *, const char*);

#ifndef SOAP_TYPE_mss__DataType
#define SOAP_TYPE_mss__DataType (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__DataType(struct soap*, const struct mss__DataType *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__DataType(struct soap*, struct mss__DataType *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__DataType(struct soap*, const struct mss__DataType *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__DataType(struct soap*, const char*, int, const struct mss__DataType *, const char*);
SOAP_FMAC3 struct mss__DataType * SOAP_FMAC4 soap_get_mss__DataType(struct soap*, struct mss__DataType *, const char*, const char*);
SOAP_FMAC3 struct mss__DataType * SOAP_FMAC4 soap_in_mss__DataType(struct soap*, const char*, struct mss__DataType *, const char*);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTomss__MSS_USCOREStatusResp
#define SOAP_TYPE_PointerTomss__MSS_USCOREStatusResp (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__MSS_USCOREStatusResp(struct soap*, struct mss__MSS_USCOREStatusResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__MSS_USCOREStatusResp(struct soap*, struct mss__MSS_USCOREStatusResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__MSS_USCOREStatusResp(struct soap*, const char *, int, struct mss__MSS_USCOREStatusResp *const*, const char *);
SOAP_FMAC3 struct mss__MSS_USCOREStatusResp ** SOAP_FMAC4 soap_get_PointerTomss__MSS_USCOREStatusResp(struct soap*, struct mss__MSS_USCOREStatusResp **, const char*, const char*);
SOAP_FMAC3 struct mss__MSS_USCOREStatusResp ** SOAP_FMAC4 soap_in_PointerTomss__MSS_USCOREStatusResp(struct soap*, const char*, struct mss__MSS_USCOREStatusResp **, const char*);

#ifndef SOAP_TYPE_PointerTomss__MSS_USCORESignatureResp
#define SOAP_TYPE_PointerTomss__MSS_USCORESignatureResp (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__MSS_USCORESignatureResp(struct soap*, struct mss__MSS_USCORESignatureResp *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__MSS_USCORESignatureResp(struct soap*, struct mss__MSS_USCORESignatureResp *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__MSS_USCORESignatureResp(struct soap*, const char *, int, struct mss__MSS_USCORESignatureResp *const*, const char *);
SOAP_FMAC3 struct mss__MSS_USCORESignatureResp ** SOAP_FMAC4 soap_get_PointerTomss__MSS_USCORESignatureResp(struct soap*, struct mss__MSS_USCORESignatureResp **, const char*, const char*);
SOAP_FMAC3 struct mss__MSS_USCORESignatureResp ** SOAP_FMAC4 soap_in_PointerTomss__MSS_USCORESignatureResp(struct soap*, const char*, struct mss__MSS_USCORESignatureResp **, const char*);

#ifndef SOAP_TYPE_PointerTomss__SignatureProfileComparisonType
#define SOAP_TYPE_PointerTomss__SignatureProfileComparisonType (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__SignatureProfileComparisonType(struct soap*, enum mss__SignatureProfileComparisonType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__SignatureProfileComparisonType(struct soap*, enum mss__SignatureProfileComparisonType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__SignatureProfileComparisonType(struct soap*, const char *, int, enum mss__SignatureProfileComparisonType *const*, const char *);
SOAP_FMAC3 enum mss__SignatureProfileComparisonType ** SOAP_FMAC4 soap_get_PointerTomss__SignatureProfileComparisonType(struct soap*, enum mss__SignatureProfileComparisonType **, const char*, const char*);
SOAP_FMAC3 enum mss__SignatureProfileComparisonType ** SOAP_FMAC4 soap_in_PointerTomss__SignatureProfileComparisonType(struct soap*, const char*, enum mss__SignatureProfileComparisonType **, const char*);

#ifndef SOAP_TYPE_PointerTomss__KeyReferenceType
#define SOAP_TYPE_PointerTomss__KeyReferenceType (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__KeyReferenceType(struct soap*, struct mss__KeyReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__KeyReferenceType(struct soap*, struct mss__KeyReferenceType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__KeyReferenceType(struct soap*, const char *, int, struct mss__KeyReferenceType *const*, const char *);
SOAP_FMAC3 struct mss__KeyReferenceType ** SOAP_FMAC4 soap_get_PointerTomss__KeyReferenceType(struct soap*, struct mss__KeyReferenceType **, const char*, const char*);
SOAP_FMAC3 struct mss__KeyReferenceType ** SOAP_FMAC4 soap_in_PointerTomss__KeyReferenceType(struct soap*, const char*, struct mss__KeyReferenceType **, const char*);

#ifndef SOAP_TYPE_PointerTomss__DataType
#define SOAP_TYPE_PointerTomss__DataType (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__DataType(struct soap*, struct mss__DataType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__DataType(struct soap*, struct mss__DataType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__DataType(struct soap*, const char *, int, struct mss__DataType *const*, const char *);
SOAP_FMAC3 struct mss__DataType ** SOAP_FMAC4 soap_get_PointerTomss__DataType(struct soap*, struct mss__DataType **, const char*, const char*);
SOAP_FMAC3 struct mss__DataType ** SOAP_FMAC4 soap_in_PointerTomss__DataType(struct soap*, const char*, struct mss__DataType **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__positiveInteger
#define SOAP_TYPE_PointerToxsd__positiveInteger (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__positiveInteger(struct soap*, unsigned long *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__positiveInteger(struct soap*, unsigned long *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__positiveInteger(struct soap*, const char *, int, unsigned long *const*, const char *);
SOAP_FMAC3 unsigned long ** SOAP_FMAC4 soap_get_PointerToxsd__positiveInteger(struct soap*, unsigned long **, const char*, const char*);
SOAP_FMAC3 unsigned long ** SOAP_FMAC4 soap_in_PointerToxsd__positiveInteger(struct soap*, const char*, unsigned long **, const char*);

#ifndef SOAP_TYPE_PointerTomss__SignatureType
#define SOAP_TYPE_PointerTomss__SignatureType (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__SignatureType(struct soap*, struct mss__SignatureType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__SignatureType(struct soap*, struct mss__SignatureType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__SignatureType(struct soap*, const char *, int, struct mss__SignatureType *const*, const char *);
SOAP_FMAC3 struct mss__SignatureType ** SOAP_FMAC4 soap_get_PointerTomss__SignatureType(struct soap*, struct mss__SignatureType **, const char*, const char*);
SOAP_FMAC3 struct mss__SignatureType ** SOAP_FMAC4 soap_in_PointerTomss__SignatureType(struct soap*, const char*, struct mss__SignatureType **, const char*);

#ifndef SOAP_TYPE_PointerTomss__mssURIType
#define SOAP_TYPE_PointerTomss__mssURIType (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__mssURIType(struct soap*, struct mss__mssURIType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__mssURIType(struct soap*, struct mss__mssURIType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__mssURIType(struct soap*, const char *, int, struct mss__mssURIType *const*, const char *);
SOAP_FMAC3 struct mss__mssURIType ** SOAP_FMAC4 soap_get_PointerTomss__mssURIType(struct soap*, struct mss__mssURIType **, const char*, const char*);
SOAP_FMAC3 struct mss__mssURIType ** SOAP_FMAC4 soap_in_PointerTomss__mssURIType(struct soap*, const char*, struct mss__mssURIType **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__base64Binary
#define SOAP_TYPE_PointerToxsd__base64Binary (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__base64Binary(struct soap*, const char *, int, struct xsd__base64Binary *const*, const char *);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_get_PointerToxsd__base64Binary(struct soap*, struct xsd__base64Binary **, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary ** SOAP_FMAC4 soap_in_PointerToxsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary **, const char*);

#ifndef SOAP_TYPE_mss__StatusDetailType
#define SOAP_TYPE_mss__StatusDetailType (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_mss__StatusDetailType(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_mss__StatusDetailType(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_mss__StatusDetailType(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_mss__StatusDetailType(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_mss__StatusDetailType(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_mss__StatusDetailType(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTomss__DigestAlgAndValueType
#define SOAP_TYPE_PointerTomss__DigestAlgAndValueType (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTomss__DigestAlgAndValueType(struct soap*, struct mss__DigestAlgAndValueType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTomss__DigestAlgAndValueType(struct soap*, struct mss__DigestAlgAndValueType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTomss__DigestAlgAndValueType(struct soap*, const char *, int, struct mss__DigestAlgAndValueType *const*, const char *);
SOAP_FMAC3 struct mss__DigestAlgAndValueType ** SOAP_FMAC4 soap_get_PointerTomss__DigestAlgAndValueType(struct soap*, struct mss__DigestAlgAndValueType **, const char*, const char*);
SOAP_FMAC3 struct mss__DigestAlgAndValueType ** SOAP_FMAC4 soap_in_PointerTomss__DigestAlgAndValueType(struct soap*, const char*, struct mss__DigestAlgAndValueType **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__dateTime(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__dateTime(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__dateTime(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
