/* soapStub.h
   Generated by gSOAP 2.7.9b from /home/veiko/MSSP_GW/src/MSSP_GW.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_mss__SignatureProfileComparisonType
#define SOAP_TYPE_mss__SignatureProfileComparisonType (19)
/* mss:SignatureProfileComparisonType */
enum mss__SignatureProfileComparisonType {exact = 0, minimum = 1, better = 2};
#endif

#ifndef SOAP_TYPE_mss__MessagingModeType
#define SOAP_TYPE_mss__MessagingModeType (20)
/* mss:MessagingModeType */
enum mss__MessagingModeType {synch = 0, asynchClientServer = 1, asynchServerServer = 2};
#endif

/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (21)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_mss__DataType
#define SOAP_TYPE_mss__DataType (23)
/* Primitive mss:DataType schema type: */
struct mss__DataType
{
	char *__item;
	char *mss__MimeType;	/* optional attribute of type xsd:string */
	char *mss__Encoding;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mss__MeshMemberType
#define SOAP_TYPE_mss__MeshMemberType (24)
/* mss:MeshMemberType */
struct mss__MeshMemberType
{
	char *mss__DNSName;	/* optional element of type xsd:string */
	char *mss__IPAddress;	/* optional element of type xsd:string */
	char *mss__URI;	/* optional element of type xsd:string */
	char *mss__IdentifierString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mss__MobileUserType
#define SOAP_TYPE_mss__MobileUserType (25)
/* mss:MobileUserType */
struct mss__MobileUserType
{
	struct mss__MeshMemberType mss__IdentityIssuer;	/* required element of type mss:MeshMemberType */
	char *mss__UserIdentifier;	/* optional element of type xsd:string */
	struct mss__MeshMemberType mss__HomeMSSP;	/* required element of type mss:MeshMemberType */
	char *mss__MSISDN;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_DigestMethodType
#define SOAP_TYPE_DigestMethodType (26)
/* DigestMethodType */
struct DigestMethodType
{
	char *Algorithm;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mss__DigestAlgAndValueType
#define SOAP_TYPE_mss__DigestAlgAndValueType (27)
/* mss:DigestAlgAndValueType */
struct mss__DigestAlgAndValueType
{
	struct DigestMethodType DigestMethod;	/* required element of type DigestMethodType */
	struct xsd__base64Binary DigestValue;	/* required element of type xsd:base64Binary */
};
#endif

#ifndef SOAP_TYPE_mss__mssURIType
#define SOAP_TYPE_mss__mssURIType (28)
/* mss:mssURIType */
struct mss__mssURIType
{
	char *mss__mssUri;	/* optional element of type xsd:string */
	struct mss__DigestAlgAndValueType *DigestAlgAndValue;	/* optional element of type mss:DigestAlgAndValueType */
};
#endif

#ifndef SOAP_TYPE_mss__AP_InfoType
#define SOAP_TYPE_mss__AP_InfoType (30)
/* mss:AP-InfoType */
struct mss__AP_InfoType
{
	char *AP_USCOREID;	/* optional attribute of type xsd:string */
	char *AP_USCORETransID;	/* optional attribute of type xsd:string */
	char *AP_USCOREPWD;	/* optional attribute of type xsd:string */
	char *Instant;	/* optional attribute of type xsd:dateTime */
	char *AP_USCOREURL;	/* optional attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mss__MSSP_InfoType
#define SOAP_TYPE_mss__MSSP_InfoType (31)
/* mss:MSSP-InfoType */
struct mss__MSSP_InfoType
{
	struct mss__MeshMemberType MSSP_USCOREID;	/* required element of type mss:MeshMemberType */
	char *Instant;	/* optional attribute of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_mss__KeyReferenceType
#define SOAP_TYPE_mss__KeyReferenceType (32)
/* mss:KeyReferenceType */
struct mss__KeyReferenceType
{
	char *CertificateURL;	/* optional element of type xsd:string */
	char *CertificateIssuerDN;	/* optional element of type xsd:string */
	struct mss__DigestAlgAndValueType *HashOfUsersPublicKey;	/* optional element of type mss:DigestAlgAndValueType */
	struct mss__DigestAlgAndValueType *HashOfCAPublicKey;	/* optional element of type mss:DigestAlgAndValueType */
};
#endif

#ifndef SOAP_TYPE_mss__StatusCodeType
#define SOAP_TYPE_mss__StatusCodeType (34)
/* Primitive mss:StatusCodeType schema type: */
struct mss__StatusCodeType
{
	char *__item;
	int Value;	/* optional attribute of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_mss__StatusType
#define SOAP_TYPE_mss__StatusType (35)
/* mss:StatusType */
struct mss__StatusType
{
	struct mss__StatusCodeType StatusCode;	/* required element of type mss:StatusCodeType */
	char *StatusMessage;	/* optional element of type xsd:string */
	char *StatusDetail;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mss__SignatureType
#define SOAP_TYPE_mss__SignatureType (36)
/* mss:SignatureType */
struct mss__SignatureType
{
	char *XMLSignature;	/* optional element of type xsd:string */
	struct xsd__base64Binary *Base64Signature;	/* optional element of type xsd:base64Binary */
	char *XAdESSignature;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_mss__MSS_USCORESignatureResp
#define SOAP_TYPE_mss__MSS_USCORESignatureResp (38)
/* mss:MSS_SignatureResp */
struct mss__MSS_USCORESignatureResp
{
	struct mss__AP_InfoType AP_USCOREInfo;	/* RPC return element */	/* required element of type mss:AP-InfoType */
	struct mss__MSSP_InfoType MSSP_USCOREInfo;	/* required element of type mss:MSSP-InfoType */
	unsigned long MajorVersion;	/* optional attribute of type xsd:positiveInteger */
	unsigned long MinorVersion;	/* optional attribute of type xsd:positiveInteger */
	struct mss__MobileUserType MobileUser;	/* required element of type mss:MobileUserType */
	struct mss__StatusType Status;	/* required element of type mss:StatusType */
	struct mss__mssURIType *SignatureProfile;	/* optional element of type mss:mssURIType */
	struct mss__SignatureType *MSS_USCORESignature;	/* optional element of type mss:SignatureType */
	unsigned long MSSP_USCORETransID;	/* required element of type xsd:positiveInteger */
};
#endif

#ifndef SOAP_TYPE_mss__MSS_USCORESignatureReq
#define SOAP_TYPE_mss__MSS_USCORESignatureReq (47)
/* mss:MSS_SignatureReq */
struct mss__MSS_USCORESignatureReq
{
	unsigned long MajorVersion;	/* optional attribute of type xsd:positiveInteger */
	unsigned long MinorVersion;	/* optional attribute of type xsd:positiveInteger */
	char *ValidityDate;	/* optional attribute of type xsd:dateTime */
	unsigned long *TimeOut;	/* optional attribute of type xsd:positiveInteger */
	enum mss__MessagingModeType MessagingMode;	/* optional attribute of type mss:MessagingModeType */
	struct mss__AP_InfoType AP_USCOREInfo;	/* required element of type mss:AP-InfoType */
	struct mss__MSSP_InfoType MSSP_USCOREInfo;	/* required element of type mss:MSSP-InfoType */
	struct mss__MobileUserType MobileUser;	/* required element of type mss:MobileUserType */
	struct mss__DataType DataToBeSigned;	/* required element of type mss:DataType */
	struct mss__DataType *DataToBeDisplayed;	/* optional element of type mss:DataType */
	struct mss__mssURIType *SignatureProfile;	/* optional element of type mss:mssURIType */
	struct mss__mssURIType *mssFormat;	/* optional element of type mss:mssURIType */
	struct mss__KeyReferenceType *KeyReference;	/* optional element of type mss:KeyReferenceType */
	enum mss__SignatureProfileComparisonType *mss__SignatureProfileComparison;	/* optional element of type mss:SignatureProfileComparisonType */
};
#endif

#ifndef SOAP_TYPE_mss__MSS_USCOREStatusResp
#define SOAP_TYPE_mss__MSS_USCOREStatusResp (48)
/* mss:MSS_StatusResp */
struct mss__MSS_USCOREStatusResp
{
	struct mss__AP_InfoType AP_USCOREInfo;	/* RPC return element */	/* required element of type mss:AP-InfoType */
	struct mss__MSSP_InfoType MSSP_USCOREInfo;	/* required element of type mss:MSSP-InfoType */
	unsigned long MajorVersion;	/* optional attribute of type xsd:positiveInteger */
	unsigned long MinorVersion;	/* optional attribute of type xsd:positiveInteger */
	struct mss__MobileUserType MobileUser;	/* required element of type mss:MobileUserType */
	struct mss__StatusType Status;	/* required element of type mss:StatusType */
	struct mss__SignatureType *MSS_USCORESignature;	/* optional element of type mss:SignatureType */
};
#endif

#ifndef SOAP_TYPE_mss__MSS_USCOREStatusReq
#define SOAP_TYPE_mss__MSS_USCOREStatusReq (51)
/* mss:MSS_StatusReq */
struct mss__MSS_USCOREStatusReq
{
	unsigned long MajorVersion;	/* required element of type xsd:positiveInteger */
	unsigned long MinorVersion;	/* required element of type xsd:positiveInteger */
	struct mss__AP_InfoType AP_USCOREInfo;	/* required element of type mss:AP-InfoType */
	struct mss__MSSP_InfoType MSSP_USCOREInfo;	/* required element of type mss:MSSP-InfoType */
	unsigned long MSSP_USCORETransID;	/* required element of type xsd:positiveInteger */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (54)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (55)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (57)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (58)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (59)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (6)
typedef char *xsd__string;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (7)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (9)
typedef float xsd__float;
#endif

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (11)
typedef long xsd__int;
#endif

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (14)
typedef unsigned char xsd__boolean;
#endif

#ifndef SOAP_TYPE_xsd__positiveInteger
#define SOAP_TYPE_xsd__positiveInteger (16)
typedef unsigned long xsd__positiveInteger;
#endif

#ifndef SOAP_TYPE_XML
#define SOAP_TYPE_XML (17)
typedef char *XML;
#endif

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (18)
typedef char *xsd__dateTime;
#endif

#ifndef SOAP_TYPE_mss__StatusDetailType
#define SOAP_TYPE_mss__StatusDetailType (33)
typedef char *mss__StatusDetailType;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 mss__MSS_USCORESignatureReq(struct soap*, unsigned long MajorVersion, unsigned long MinorVersion, char *ValidityDate, unsigned long *TimeOut, enum mss__MessagingModeType MessagingMode, struct mss__AP_InfoType AP_USCOREInfo, struct mss__MSSP_InfoType MSSP_USCOREInfo, struct mss__MobileUserType MobileUser, struct mss__DataType DataToBeSigned, struct mss__DataType *DataToBeDisplayed, struct mss__mssURIType *SignatureProfile, struct mss__mssURIType *mssFormat, struct mss__KeyReferenceType *KeyReference, enum mss__SignatureProfileComparisonType *mss__SignatureProfileComparison, struct mss__MSS_USCORESignatureResp *resp);

SOAP_FMAC5 int SOAP_FMAC6 mss__MSS_USCOREStatusReq(struct soap*, unsigned long MajorVersion, unsigned long MinorVersion, struct mss__AP_InfoType AP_USCOREInfo, struct mss__MSSP_InfoType MSSP_USCOREInfo, unsigned long MSSP_USCORETransID, struct mss__MSS_USCOREStatusResp *response);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_mss__MSS_USCORESignatureReq(struct soap *soap, const char *soap_endpoint, const char *soap_action, unsigned long MajorVersion, unsigned long MinorVersion, char *ValidityDate, unsigned long *TimeOut, enum mss__MessagingModeType MessagingMode, struct mss__AP_InfoType AP_USCOREInfo, struct mss__MSSP_InfoType MSSP_USCOREInfo, struct mss__MobileUserType MobileUser, struct mss__DataType DataToBeSigned, struct mss__DataType *DataToBeDisplayed, struct mss__mssURIType *SignatureProfile, struct mss__mssURIType *mssFormat, struct mss__KeyReferenceType *KeyReference, enum mss__SignatureProfileComparisonType *mss__SignatureProfileComparison, struct mss__MSS_USCORESignatureResp *resp);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_mss__MSS_USCOREStatusReq(struct soap *soap, const char *soap_endpoint, const char *soap_action, unsigned long MajorVersion, unsigned long MinorVersion, struct mss__AP_InfoType AP_USCOREInfo, struct mss__MSSP_InfoType MSSP_USCOREInfo, unsigned long MSSP_USCORETransID, struct mss__MSS_USCOREStatusResp *response);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_mss__MSS_USCORESignatureReq(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_mss__MSS_USCOREStatusReq(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
