######################################################################
# Automatically generated by qmake (1.04a) to 30. jan 22:59:06 2003
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += data.h modules.h modulefactory.h
SOURCES += data.cpp main.cpp modules.cpp modulefactory.cpp

# Leave away .. in your own code. See comment in ../qsa.prf.
load( ../qsa )

