######################################################################
# Automatically generated by qmake (1.07a) ma 15. des 16:05:20 2003
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += wrappers.cpp

load(../qsa)
