######################################################################
# Automatically generated by qmake (1.04a) Tue Dec 10 16:10:06 2002
######################################################################

TEMPLATE = app
CONFIG -= moc
CONFIG += console
INCLUDEPATH += . ../../qt/include

# Input
SOURCES += main.cpp configutils.cpp
HEADERS += configutils.h
